import { readFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (p) => readFileSync(path.join(root, p), 'utf8')
const assert = (condition, message) => { if (!condition) throw new Error(message) }

const model = read('docs/.vitepress/theme/practice/practice-model.mjs')
const safety = read('docs/.vitepress/theme/practice/practice-safety.mjs')
const reduction = read('docs/.vitepress/theme/styles/practice-reduction.css')
const accessibilityCss = read('docs/.vitepress/theme/styles/practice-accessibility.css')
const safetyReduction = read('docs/.vitepress/theme/practice/practice-safety-reduction.ts')
const reviewReduction = read('docs/.vitepress/theme/practice/practice-review-reduction.ts')
const stageReduction = read('docs/.vitepress/theme/practice/practice-stage-reduction.ts')
const accessibility = read('docs/.vitepress/theme/practice/practice-accessibility.ts')
const themeIndex = read('docs/.vitepress/theme/index.ts')
const tests = read('tests/practice-form-fields.test.mjs')
const singleYellowTest = read('tests/practice-safety-single-yellow.test.mjs')
const stageSingleYellowTest = read('tests/practice-stage-single-yellow.test.mjs')
const e2e = read('scripts/e2e-practice-reduction.mjs')
const safetyE2E = read('scripts/e2e-practice-safety-reduction.mjs')
const reviewE2E = read('scripts/e2e-practice-review-reduction.mjs')
const stageE2E = read('scripts/e2e-practice-stage-reduction.mjs')
const accessibilityE2E = read('scripts/e2e-practice-accessibility.mjs')
const packageJson = JSON.parse(read('package.json'))

assert(model.includes("emotionState: 'not_observed'"), '新记录不得默认写入“情绪稳定”')
assert(model.includes("nextStep: 'not_decided'"), '新记录不得默认写入“下次继续”')
assert(model.includes("const EMOTION_STATES = new Set(['not_observed'"), '情绪字段缺少未记录语义')
assert(model.includes("const NEXT_STEPS = new Set(['not_decided'"), '下次决定缺少未决定语义')
assert(model.includes('issues: skipped ? []'), '不练记录必须清理本次练习异常')
assert(model.includes("severity: skipped ? 'none'"), '不练记录必须清理安全分流')
assert(model.includes("nextStep: skipped ? 'not_decided'"), '不练记录不得残留下次决定')

assert(safety.includes("code: 'yellow_event'"), '单次黄色事件不能缺少独立复盘规则')
assert(safety.includes('不应因为只出现一次就被当作“状态稳定”'), '单次黄色事件不得被稳定提示覆盖')
assert(singleYellowTest.includes('单次黄色事件不会被稳定提示覆盖'), '自动测试未覆盖单次黄色事件复盘语义')
assert(stageSingleYellowTest.includes('30天复盘保留单次黄色安全提醒'), '30天自动测试未覆盖单次黄色安全优先级')

assert(reduction.includes('.pj-today__meta > span:first-child'), '首屏减负未移除今日卡阶段方向')
assert(reduction.includes('option[value="stable"]'), '首屏减负未退出日常情绪字段')
assert(reduction.includes('option[value="continue"]'), '首屏减负未退出日常下次决定字段')
assert(reduction.includes('.pj-form:not(.pj-safety-expanded) .pj-issues'), '正常记录未折叠异常列表')
assert(reduction.includes('.pj-form:not(.pj-safety-expanded) .pj-grid--small'), '正常记录未折叠安全分流')
assert(reduction.includes('.pj-safety-skipped .pj-redbox'), '不练记录仍可能显示练习红色事件提示')
assert(reduction.includes('.pj-review-stats-details'), '7天数字明细未进入渐进展示')
assert(reduction.includes('.pj-review-ai-details'), '7天 AI 材料未进入渐进展示')
assert(reduction.includes('.pj-review-empty-issues'), '空重复问题未做轻量展示')
assert(reduction.includes('.pj-stage-evidence-details'), '30天统计/分布/观察维度未进入记录依据折叠区')
assert(reduction.includes('.pj-stage-ai-details'), '30天 AI 材料未进入渐进展示')
assert(reduction.includes('[data-stage-kind="safety"]'), '30天安全提醒缺少最高优先展示层')
assert(reduction.includes('[data-stage-kind="decision"]'), '30天当前建议缺少次级展示层')
assert(themeIndex.includes("import './styles/practice-reduction.css'"), '主题入口未加载实践减负样式')
assert(themeIndex.includes("import './styles/practice-accessibility.css'"), '主题入口未加载实践可访问性样式')
assert(themeIndex.includes('installPracticeSafetyReduction'), '主题入口未启用异常安全渐进展开')
assert(themeIndex.includes('installPracticeReviewReduction'), '主题入口未启用7天复盘渐进展示')
assert(themeIndex.includes('installPracticeStageReduction'), '主题入口未启用30天复盘渐进展示')
assert(themeIndex.includes('installPracticeAccessibility'), '主题入口未启用实践可访问性增强')

assert(safetyReduction.includes('异常与安全（没有则跳过）'), '异常安全入口缺少正常态极简文案')
assert(safetyReduction.includes('需要安全核对 · 已展开'), '异常安全入口缺少提醒态文案')
assert(safetyReduction.includes('const needsAttention ='), '异常安全层缺少统一需要关注判断')
assert(safetyReduction.includes('setExpanded(button, form, true)'), '需要关注时不能自动展开异常区')
assert(safetyReduction.includes('setButtonText'), '渐进展开同步必须保持幂等，避免 MutationObserver 文案循环')
assert(!/severity\.value\s*=\s*['\"](?:yellow|red)/.test(safetyReduction), '渐进展开层不得自动替用户判定黄色或红色')

assert(reviewReduction.includes('先看规则提醒和重复问题'), '7天复盘缺少首要信息引导')
assert(reviewReduction.includes('查看7天数据细节'), '7天数字没有按需展开入口')
assert(reviewReduction.includes('AI复盘材料（可选）'), 'AI复盘材料缺少低频入口语义')
assert(reviewReduction.includes("rules.dataset.reviewKind = 'rules'"), '规则型复盘必须保持首要可见')
assert(reviewReduction.includes("issues.dataset.reviewKind = 'issues'"), '重复问题必须保持首要可见')
assert(!/rules\.hidden\s*=\s*true/.test(reviewReduction), '减负层不得隐藏规则型复盘')
assert(!/issues\.hidden\s*=\s*true/.test(reviewReduction), '减负层不得隐藏真实重复问题')

assert(stageReduction.includes("tab.textContent = '30天复盘'"), '30天入口仍可能保留“阶段/晋级”式命名')
assert(stageReduction.includes("kicker.textContent = '当前建议'"), '30天长期分流仍显示“阶段方向”')
assert(stageReduction.includes('查看30天记录依据（不是等级）'), '30天记录依据缺少非等级语义')
assert(stageReduction.includes('AI阶段复盘材料（可选）'), '30天 AI 材料缺少低频入口语义')
assert(stageReduction.includes('不是修炼境界、认证、完成度或自动解锁'), '30天当前建议缺少非等级/非认证边界')
assert(stageReduction.includes('长期建议不能覆盖这类安全记录'), '30天黄色安全事件缺少长期建议覆盖保护')
assert(stageReduction.includes('安全处理优先于任何长期建议'), '30天红色安全事件缺少最高优先级')

assert(accessibility.includes("tab.setAttribute('aria-controls'"), '标签页缺少 aria-controls 关联')
assert(accessibility.includes("panel.setAttribute('role', 'tabpanel')"), '标签内容区缺少 tabpanel 语义')
assert(accessibility.includes("panel.setAttribute('aria-labelledby'"), '标签内容区缺少 aria-labelledby 关联')
assert(accessibility.includes("input.focus({ preventScroll: true })"), '今日入口动作后未提供键盘焦点转移')
assert(accessibility.includes("urgent ? 'alert' : 'status'"), '红色提示未区分紧急播报语义')
assert(accessibility.includes("urgent ? 'assertive' : 'polite'"), '红色提示未使用 assertive aria-live')
assert(accessibilityCss.includes('@media (pointer: coarse)'), '缺少粗指针/触控环境尺寸规则')
assert(accessibilityCss.includes('min-height: 44px'), '触控目标未设置至少44px基线')
assert(accessibilityCss.includes(':focus-visible'), '缺少键盘焦点可见样式')

assert(tests.includes('新记录默认不虚构情绪状态或下次决定'), '自动测试未覆盖默认不推断字段')
assert(tests.includes('清理练习观察、异常和后续决定'), '自动测试未覆盖不练记录异常清理')
assert(e2e.includes('阶段方向退出今日卡'), 'Chromium 未覆盖今日卡阶段方向减法')
assert(e2e.includes('情绪/下次决定退出日常表单'), 'Chromium 未覆盖低价值字段退出日常表单')
assert(e2e.includes("emotionState !== 'not_observed'"), 'Chromium 未校验保存后的情绪未记录值')
assert(e2e.includes("nextStep !== 'not_decided'"), 'Chromium 未校验保存后的下次未决定值')
assert(safetyE2E.includes('正常安全区折叠'), 'Chromium 未覆盖正常状态安全区折叠')
assert(safetyE2E.includes('草稿安全提醒未自动展开'), 'Chromium 未覆盖异常提醒自动展开')
assert(safetyE2E.includes('不练记录仍携带练习异常或后续决定'), 'Chromium 未覆盖不练记录异常清理')
assert(reviewE2E.includes('规则提醒没有成为首要内容'), 'Chromium 未覆盖7天规则提醒首要展示')
assert(reviewE2E.includes('数字或AI材料没有默认后移'), 'Chromium 未覆盖7天数字/AI默认折叠')
assert(reviewE2E.includes('真实重复问题被减负层隐藏'), 'Chromium 未覆盖真实重复问题保持可见')
assert(reviewE2E.includes('安全规则提醒没有直接可见'), 'Chromium 未覆盖单次黄色规则提醒直接可见')
assert(stageE2E.includes('30天入口仍保留晋级式命名'), 'Chromium 未覆盖30天入口减等级语义')
assert(stageE2E.includes('单次黄色事件没有优先显示'), 'Chromium 未覆盖30天单次黄色安全优先')
assert(stageE2E.includes('红色安全事件没有覆盖长期阶段进度'), 'Chromium 未覆盖30天红色安全覆盖')
assert(stageE2E.includes('30天记录依据展开后不完整'), 'Chromium 未覆盖30天记录依据可恢复')
assert(accessibilityE2E.includes('标签页与面板关系不完整'), 'Chromium 未覆盖 tab/tabpanel 关系')
assert(accessibilityE2E.includes('存在无可访问名称的可见表单控件'), 'Chromium 未覆盖表单控件可访问名称')
assert(accessibilityE2E.includes('键盘焦点没有进入日期字段'), 'Chromium 未覆盖今日入口后的焦点管理')
assert(accessibilityE2E.includes('红色安全阻断未使用紧急播报语义'), 'Chromium 未覆盖红色 alert/assertive 语义')
assert(accessibilityE2E.includes('触控目标小于44px'), 'Chromium 未覆盖390px触控目标尺寸')
assert(String(packageJson.scripts?.['test:e2e:daily'] || '').includes('e2e-practice-safety-reduction.mjs'), '每日 E2E 尚未纳入异常安全减负回归')
assert(String(packageJson.scripts?.['test:e2e:daily'] || '').includes('e2e-practice-review-reduction.mjs'), '实践减负 E2E 尚未纳入7天复盘回归')
assert(String(packageJson.scripts?.['test:e2e:daily'] || '').includes('e2e-practice-stage-reduction.mjs'), '实践减负 E2E 尚未纳入30天复盘回归')
assert(String(packageJson.scripts?.['test:e2e:daily'] || '').includes('e2e-practice-accessibility.mjs'), '实践主链尚未纳入可访问性回归')

console.log('[实践减负检查通过] 日常、异常安全、7天、30天与可访问性均受质量门保护；安全优先，记录依据不作为等级。')